Repository Nixtla/utilsforecast, pull requests merged in 2024-11, with the labels that each got.

#133 enh: ignore pandas perf warnings on unvectorized offsets
  nbs/processing.ipynb
  settings.ini
  utilsforecast/__init__.py
  utilsforecast/processing.py
Labels: enhancement

#136 Add MSSE and RMSSE losses
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  action_files/nbdev_test
  nbs/losses.ipynb
  utilsforecast/_modidx.py
  utilsforecast/losses.py
Labels: feature

#138 fix: invalid escape sequence in string
  nbs/losses.ipynb
  nbs/plotting.ipynb
  utilsforecast/losses.py
  utilsforecast/plotting.py
Labels: fix

#139 deps(pandas): address frequency alias deprecations in `generate_series`
  nbs/compat.ipynb
  nbs/data.ipynb
  nbs/imgs/plotting.png
  nbs/plotting.ipynb
  utilsforecast/compat.py
  utilsforecast/data.py
Labels: dependencies
