Repository Nixtla/utilsforecast, pull requests merged in 2024-07, with the labels that each got.

#99 add agg_fn to evaluate
  nbs/evaluation.ipynb
  utilsforecast/evaluation.py
Labels: feature

#92 [FEAT] Add stylesheet argument
  nbs/imgs/plotting.png
  nbs/plotting.ipynb
  utilsforecast/plotting.py
Labels: enhancement

#90 remove target transforms
  nbs/target_transforms.ipynb
  settings.ini
  setup.py
  utilsforecast/_modidx.py
  utilsforecast/target_transforms.py
Labels: breaking change

#106 drop na for pandas in counts_by_id
  nbs/processing.ipynb
  utilsforecast/processing.py
Labels: fix

#107 use utc to handle timezones in fill_gaps
  .github/workflows/lint.yaml
  nbs/preprocessing.ipynb
  utilsforecast/preprocessing.py
Labels: enhancement

#108 add time_features to feature engineering
  nbs/feature_engineering.ipynb
  nbs/processing.ipynb
  utilsforecast/_modidx.py
  utilsforecast/feature_engineering.py
  utilsforecast/processing.py
Labels: feature

#109 accept plot object in plot_series
  nbs/plotting.ipynb
  utilsforecast/plotting.py
Labels: enhancement

#111 support returning multiple time features from function
  nbs/compat.ipynb
  nbs/feature_engineering.ipynb
  utilsforecast/compat.py
  utilsforecast/feature_engineering.py
Labels: enhancement

#112 generate ranges with time_unit for polars in fill_gaps
  nbs/preprocessing.ipynb
  utilsforecast/preprocessing.py
Labels: fix
