Repository Nixtla/utilsforecast, pull requests merged in 2024-02, with the labels that each got.

#60 add drop_columns to address polars DeprecationWarning
  .gitignore
  nbs/processing.ipynb
  utilsforecast/_modidx.py
  utilsforecast/processing.py
Labels: dependencies

#63 correct calculation of quantile loss
  nbs/losses.ipynb
  utilsforecast/losses.py
Labels: fix

#64 fix multiple models in mqloss
  nbs/losses.ipynb
  utilsforecast/losses.py
Labels: fix

#66 fix probabilistic losses
  .github/workflows/ci.yaml
  environment.yml
  nbs/evaluation.ipynb
  nbs/losses.ipynb
  settings.ini
  utilsforecast/_modidx.py
  utilsforecast/evaluation.py
  utilsforecast/losses.py
Labels: breaking change
