Repository Nixtla/utilsforecast, pull requests merged in 2025-02, with the labels that each got.

#155 deps(python): drop 3.8 and support 3.13
  .github/workflows/ci.yaml
  settings.ini
Labels: dependencies

#154 fix: Validate freq parameter with data in `fill_gaps`
  nbs/preprocessing.ipynb
  utilsforecast/preprocessing.py
Labels: fix

#148 Add Scaled QL and Scaled MQL
  nbs/losses.ipynb
  utilsforecast/_modidx.py
  utilsforecast/losses.py
Labels: feature
